import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

export function shouldGenerateClaudeMd(agents: string[] = []): boolean {
  return agents.includes("claude-code");
}

function collectMarkdownFiles(dir: string): string[] {
  let entries: import("node:fs").Dirent[];
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return [];
  }

  const files: string[] = [];
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    const isDir =
      entry.isDirectory() || (entry.isSymbolicLink() && statSync(fullPath).isDirectory());
    if (isDir) {
      files.push(...collectMarkdownFiles(fullPath));
      continue;
    }

    const isFile = entry.isFile() || entry.isSymbolicLink();
    if (isFile && entry.name.toLowerCase().endsWith(".md")) {
      files.push(fullPath);
    }
  }

  return files;
}

interface FrontmatterResult {
  body: string;
  fmName: string | null;
  fmDescription: string | null;
}

function parseFrontmatter(markdown: string): FrontmatterResult {
  if (!markdown.startsWith("---")) {
    return { body: markdown, fmName: null, fmDescription: null };
  }

  const endIdx = markdown.indexOf("\n---", 3);
  if (endIdx === -1) {
    return { body: markdown, fmName: null, fmDescription: null };
  }

  const block = markdown.slice(3, endIdx);
  const body = markdown.slice(endIdx + 4).replace(/^\n+/, "");

  let fmName: string | null = null;
  let fmDescription: string | null = null;

  for (const line of block.split(/\r?\n/)) {
    const nameMatch = line.match(/^name:\s*["']?(.+?)["']?\s*$/);
    if (nameMatch) fmName = nameMatch[1];

    const descMatch = line.match(/^description:\s*["']?(.+?)["']?\s*$/);
    if (descMatch) fmDescription = descMatch[1];
  }

  return { body, fmName, fmDescription };
}

export function summarizeMarkdown(markdown: string): {
  title: string | null;
  summary: string | null;
} {
  const { body, fmName, fmDescription } = parseFrontmatter(markdown);

  const lines = body.split(/\r?\n/);
  let title: string | null = null;
  let summary: string | null = null;
  let inCodeFence = false;
  const paragraph: string[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();

    if (line.startsWith("```")) {
      inCodeFence = !inCodeFence;
      continue;
    }

    if (inCodeFence) continue;

    if (!title && line.startsWith("#")) {
      title = line.replace(/^#+\s*/, "").trim() || null;
      continue;
    }

    if (fmDescription) continue;

    if (!line) {
      if (paragraph.length > 0) {
        summary = paragraph.join(" ").trim();
        break;
      }
      continue;
    }

    if (/^#{1,6}\s/.test(line)) continue;
    if (/^[-*_]{3,}$/.test(line)) continue;
    if (/^[-*]\s+/.test(line) && paragraph.length === 0) continue;
    if (/^\d+\.\s+/.test(line) && paragraph.length === 0) continue;
    if (/^[>|`]/.test(line)) continue;

    paragraph.push(line);
  }

  if (fmDescription) {
    summary = fmDescription;
  } else if (!summary && paragraph.length > 0) {
    summary = paragraph.join(" ").trim();
  }

  if (!title) title = fmName;

  if (summary) {
    summary = summary.replace(/\s+/g, " ");
    if (summary.length > 300) {
      summary = `${summary.slice(0, 297).trimEnd()}...`;
    }
  }

  return { title, summary };
}

const SECTION_START = "<!-- autoskills:start -->";
const SECTION_END = "<!-- autoskills:end -->";

interface SkillFileEntry {
  skillName: string;
  relativePath: string;
  fileName: string;
  title: string | null;
  summary: string | null;
}

function buildSection(projectDir: string, skillsDir: string, markdownFiles: string[]): string {
  const entries: SkillFileEntry[] = [];
  for (const filePath of markdownFiles) {
    const relativePath = relative(projectDir, filePath).replaceAll("\\", "/");
    const innerPath = relative(skillsDir, filePath).replaceAll("\\", "/");
    const skillName = innerPath.split("/")[0] || "unknown-skill";
    const fileName = innerPath.split("/").slice(1).join("/") || innerPath;
    const markdown = readFileSync(filePath, "utf-8");
    const { title, summary } = summarizeMarkdown(markdown);
    entries.push({ skillName, relativePath, fileName, title, summary });
  }

  const grouped = new Map<string, SkillFileEntry[]>();
  for (const entry of entries) {
    if (!grouped.has(entry.skillName)) {
      grouped.set(entry.skillName, []);
    }
    grouped.get(entry.skillName)!.push(entry);
  }

  const lines: string[] = [
    SECTION_START,
    "",
    "Summary generated by `autoskills`. Check the full files inside `.claude/skills`.",
    "",
  ];

  for (const [, skillEntries] of grouped) {
    const main = skillEntries.find((e) => /^SKILL\.md$/i.test(e.fileName));
    const refs = skillEntries.filter((e) => e !== main);

    const heading = main?.title || refs[0]?.title || skillEntries[0].skillName;
    const description = main?.summary;

    lines.push(`## ${heading}`);
    lines.push("");

    if (description) {
      lines.push(description);
      lines.push("");
    }

    if (main) {
      lines.push(`- \`${main.relativePath}\``);
    }

    for (const ref of refs) {
      const label = ref.title || ref.fileName;
      const desc = ref.summary ? `: ${ref.summary}` : "";
      lines.push(`- \`${ref.relativePath}\`${desc}`);
    }

    lines.push("");
  }

  lines.push(SECTION_END);
  return lines.join("\n");
}

export interface GenerateResult {
  generated: boolean;
  outputPath: string;
  files: number;
}

export function generateClaudeMd(projectDir: string): GenerateResult {
  const skillsDir = join(projectDir, ".claude", "skills");
  const outputPath = join(projectDir, "CLAUDE.md");

  if (!existsSync(skillsDir)) {
    return { generated: false, outputPath, files: 0 };
  }

  const markdownFiles = collectMarkdownFiles(skillsDir).sort((a, b) => a.localeCompare(b));
  if (markdownFiles.length === 0) {
    return { generated: false, outputPath, files: 0 };
  }

  const section = buildSection(projectDir, skillsDir, markdownFiles);

  let content: string;
  if (existsSync(outputPath)) {
    const existing = readFileSync(outputPath, "utf-8");
    const startIdx = existing.indexOf(SECTION_START);
    const endIdx = existing.indexOf(SECTION_END);

    if (startIdx !== -1 && endIdx !== -1) {
      const before = existing.slice(0, startIdx);
      const after = existing.slice(endIdx + SECTION_END.length);
      content = `${before}${section}${after}`;
    } else {
      content = `${existing.trimEnd()}\n\n${section}\n`;
    }
  } else {
    content = `# CLAUDE.md\n\n${section}\n`;
  }

  writeFileSync(outputPath, content);
  return { generated: true, outputPath, files: markdownFiles.length };
}
